CREATE TABLE `characters_table` (
	`id` text PRIMARY KEY DEFAULT 'ee7da842-4bdb-4924-8af0-0f8fbc3a9efc' NOT NULL,
	`clerk_user_id` text NOT NULL,
	`name` text DEFAULT 'New Character' NOT NULL,
	`image_url` text DEFAULT '/images/portrait-placeholder.png' NOT NULL,
	`settings` text DEFAULT '{"void_enabled":false,"use_gold_coins":false}' NOT NULL,
	`derived_descriptors` text DEFAULT '{"ancestry_name":"","primary_class_name":"","primary_subclass_name":"","secondary_class_name":"","secondary_subclass_name":""}' NOT NULL,
	`ancestry_card_id` text,
	`community_card_id` text,
	`experiences` text DEFAULT '["",""]' NOT NULL,
	`primary_class_id` text,
	`primary_subclass_id` text,
	`secondary_class_id` text,
	`secondary_subclass_id` text,
	`secondary_class_domain_id_choice` text,
	`background_questions` text DEFAULT '[]' NOT NULL,
	`connections` text DEFAULT '[]' NOT NULL,
	`character_descriptions` text DEFAULT '{"clothes":"","eyes":"","body":"","skin":"","attitude":""}' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`active_armor_id` text,
	`active_primary_weapon_id` text,
	`active_secondary_weapon_id` text,
	`inventory` text DEFAULT '{"primary_weapons":{},"secondary_weapons":{},"armor":{},"loot":{},"consumables":{},"adventuring_gear":[],"gold_coins":0}' NOT NULL,
	`active_conditions` text DEFAULT '[]' NOT NULL,
	`transformation_card_id` text,
	`additional_domain_card_ids` text DEFAULT '[]' NOT NULL,
	`additional_character_modifiers` text DEFAULT '[]' NOT NULL,
	`additional_weapon_modifiers` text DEFAULT '[]' NOT NULL,
	`unarmed_attack_choices` text DEFAULT '{}' NOT NULL,
	`domain_card_choices` text DEFAULT '{}' NOT NULL,
	`domain_card_tokens` text DEFAULT '{}' NOT NULL,
	`selected_traits` text DEFAULT '{"agility":null,"strength":null,"finesse":null,"instinct":null,"presence":null,"knowledge":null}' NOT NULL,
	`marked_hp` integer DEFAULT 0 NOT NULL,
	`marked_stress` integer DEFAULT 0 NOT NULL,
	`marked_hope` integer DEFAULT 0 NOT NULL,
	`marked_armor` integer DEFAULT 0 NOT NULL,
	`loadout_domain_card_ids` text DEFAULT '[]' NOT NULL,
	`level` integer DEFAULT 1 NOT NULL,
	`level_up_domain_card_ids` text DEFAULT '{"1":{"A":null,"B":null},"2":{"A":null},"3":{"A":null},"4":{"A":null},"5":{"A":null},"6":{"A":null},"7":{"A":null},"8":{"A":null},"9":{"A":null},"10":{"A":null}}' NOT NULL,
	`level_up_choices` text DEFAULT '{"2":{"A":{"option_id":null,"marked_traits":{"A":null,"B":null},"selected_experiences":[],"selected_domain_card_id":null,"selected_subclass_upgrade":null},"B":{"option_id":null,"marked_traits":{"A":null,"B":null},"selected_experiences":[],"selected_domain_card_id":null,"selected_subclass_upgrade":null}},"3":{"A":{"option_id":null,"marked_traits":{"A":null,"B":null},"selected_experiences":[],"selected_domain_card_id":null,"selected_subclass_upgrade":null},"B":{"option_id":null,"marked_traits":{"A":null,"B":null},"selected_experiences":[],"selected_domain_card_id":null,"selected_subclass_upgrade":null}},"4":{"A":{"option_id":null,"marked_traits":{"A":null,"B":null},"selected_experiences":[],"selected_domain_card_id":null,"selected_subclass_upgrade":null},"B":{"option_id":null,"marked_traits":{"A":null,"B":null},"selected_experiences":[],"selected_domain_card_id":null,"selected_subclass_upgrade":null}},"5":{"A":{"option_id":null,"marked_traits":{"A":null,"B":null},"selected_experiences":[],"selected_domain_card_id":null,"selected_subclass_upgrade":null},"B":{"option_id":null,"marked_traits":{"A":null,"B":null},"selected_experiences":[],"selected_domain_card_id":null,"selected_subclass_upgrade":null}},"6":{"A":{"option_id":null,"marked_traits":{"A":null,"B":null},"selected_experiences":[],"selected_domain_card_id":null,"selected_subclass_upgrade":null},"B":{"option_id":null,"marked_traits":{"A":null,"B":null},"selected_experiences":[],"selected_domain_card_id":null,"selected_subclass_upgrade":null}},"7":{"A":{"option_id":null,"marked_traits":{"A":null,"B":null},"selected_experiences":[],"selected_domain_card_id":null,"selected_subclass_upgrade":null},"B":{"option_id":null,"marked_traits":{"A":null,"B":null},"selected_experiences":[],"selected_domain_card_id":null,"selected_subclass_upgrade":null}},"8":{"A":{"option_id":null,"marked_traits":{"A":null,"B":null},"selected_experiences":[],"selected_domain_card_id":null,"selected_subclass_upgrade":null},"B":{"option_id":null,"marked_traits":{"A":null,"B":null},"selected_experiences":[],"selected_domain_card_id":null,"selected_subclass_upgrade":null}},"9":{"A":{"option_id":null,"marked_traits":{"A":null,"B":null},"selected_experiences":[],"selected_domain_card_id":null,"selected_subclass_upgrade":null},"B":{"option_id":null,"marked_traits":{"A":null,"B":null},"selected_experiences":[],"selected_domain_card_id":null,"selected_subclass_upgrade":null}},"10":{"A":{"option_id":null,"marked_traits":{"A":null,"B":null},"selected_experiences":[],"selected_domain_card_id":null,"selected_subclass_upgrade":null},"B":{"option_id":null,"marked_traits":{"A":null,"B":null},"selected_experiences":[],"selected_domain_card_id":null,"selected_subclass_upgrade":null}}}' NOT NULL
);
